'use client';
import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {syncServerSession} from '@/lib/auth/session-client';
type Settings={paid_orders_enabled:boolean;support_requests_enabled:boolean;version:number;updated_at:string};
export default function AdminSettingsPage(){
 const [settings,setSettings]=useState<Settings|null>(null),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError('');setSuccess('');try{const {data:{session}}=await supabase.auth.getSession();if(session)await syncServerSession(session.access_token);const response=await fetch('/api/admin/settings',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);setSettings(data);}catch(e){setError(e instanceof Error?e.message:'Unable to load settings');}finally{setBusy(false);}}
 useEffect(()=>{void load();},[]);
 async function save(){if(!settings)return;setBusy(true);setError('');setSuccess('');try{const response=await fetch('/api/admin/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:settings.version,paid_orders_enabled:settings.paid_orders_enabled,support_requests_enabled:settings.support_requests_enabled})});const data=await response.json();if(!response.ok)throw new Error(data.error);await load();setSuccess('Settings saved.');}catch(e){setError(e instanceof Error?e.message:'Save failed');}finally{setBusy(false);}}
 return <section className="p-6 bg-card border border-border rounded-2xl text-foreground space-y-5"><h1 className="text-xl font-bold">Operational settings</h1>{error&&<p role="alert" className="text-red-600">{error}</p>}{success&&<p role="status">{success}</p>}{settings?<><label className="flex gap-3 items-center"><input type="checkbox" disabled={busy} checked={settings.paid_orders_enabled} onChange={e=>setSettings({...settings,paid_orders_enabled:e.target.checked})}/>Accept new paid orders</label><p className="text-sm">Applies to memberships, featured profiles, consultations and contact purchases. Existing payments can still be verified and fulfilled. Payment credentials must also be configured.</p><label className="flex gap-3 items-center"><input type="checkbox" disabled={busy} checked={settings.support_requests_enabled} onChange={e=>setSettings({...settings,support_requests_enabled:e.target.checked})}/>Accept new support requests</label><p className="text-sm">Members can still read existing requests and admins can reply.</p><p className="text-sm">Version {settings.version} · Saved {new Date(settings.updated_at).toLocaleString()}</p><button onClick={save} disabled={busy} className="underline">{busy?'Working…':'Save settings'}</button></>:busy?<p>Loading settings…</p>:null}<button onClick={load} disabled={busy} className="underline ml-4">Reload saved settings</button></section>;
}

