export const SUBSCRIPTION_PLANS = {
  FREE: {
    id: 'free',
    name: 'Startup Plan',
    price: 0,
    duration: 'lifetime',
    features: [
      'Create Profile',
      'Browse Profiles',
      'Receive Interests and Messages',
      'Basic Horoscope Match Percentage',
      'Limited Daily Profile Views',
    ],
  },
  SILVER: {
    id: 'silver',
    name: 'Silver Plan',
    price: 1499,
    duration: '30 Days',
    features: [
      'Filter According To Your Preferences',
      'Browse Profiles',
      'Verified Badge',
      'Send and Receive Interests & Messages',
      'View Up To 15 Contact Numbers',
      'Unlimited Horoscope Match Percentage',
      'One Detailed Horoscope Matching Report',
    ],
  },
  GOLD: {
    id: 'gold',
    name: 'Gold Plan',
    price: 2999,
    duration: '3 Months',
    features: [
      'Filter According To Your Preferences',
      'Browse Profiles',
      'Verified Badge',
      'Send and Receive Interests & Messages',
      'View Up To 30 Contact Numbers',
      'Unlimited Horoscope Match Percentage',
      'Up To 5 Detailed Horoscope Matching Reports',
      '1 Free Live/Call Horoscope Consultation',
    ],
  },
  DIAMOND: {
    id: 'diamond',
    name: 'Diamond Plan',
    price: 5999,
    duration: '6 Months',
    features: [
      'Filter According To Your Preferences',
      'Browse Profiles',
      'Verified Badge',
      'Send and Receive Interests & Messages',
      'View Up To 60 Contact Numbers',
      'Unlimited Horoscope Match Percentage',
      'Up To 10 Detailed Horoscope Matching Reports',
      '5 Free Live/Call Horoscope Consultations',
    ],
  },
};
