create table public.communities(id uuid primary key default gen_random_uuid(),religion text not null check(religion in ('Hindu','Muslim','Christian','Sikh','Buddhist','Jain')),name text not null check(length(trim(name)) between 1 and 100),is_active boolean not null default true,created_at timestamptz not null default now());
create unique index communities_religion_name on public.communities(religion,lower(name));
alter table public.communities enable row level security;
grant select on public.communities to anon,authenticated;
grant insert,update,delete on public.communities to authenticated;
grant all on public.communities to service_role;
create policy active_community_options on public.communities for select to anon,authenticated using(is_active);
create policy trusted_admin_community_writes on public.communities for all to authenticated using(private.admin_verified()) with check(private.admin_verified());
insert into public.communities(religion,name) values ('Hindu','Brahmin'),('Hindu','Iyer'),('Hindu','Iyengar'),('Hindu','Pillai'),('Hindu','Kshatriya / Rajput'),('Hindu','Vaishya'),('Hindu','Yadav'),('Hindu','Jat'),('Hindu','Maratha'),('Hindu','Nair'),('Hindu','Vokkaliga'),('Hindu','Lingayat'),('Hindu','Reddy'),('Hindu','Kamma'),('Hindu','Mudaliar'),('Hindu','Chettiar'),('Hindu','Gounder'),('Hindu','Thevar'),('Hindu','Vanniyar'),('Hindu','Nadar'),('Hindu','Ezhava'),('Hindu','Kurmi'),('Hindu','Patel / Patidar'),('Hindu','Scheduled Caste'),('Hindu','Scheduled Tribe'),('Muslim','Syed'),('Muslim','Sheikh'),('Muslim','Pathan'),('Muslim','Mughal'),('Muslim','Ansari'),('Muslim','Qureshi'),('Muslim','Mansoori'),('Muslim','Saifi'),('Muslim','Memon'),('Muslim','Bohra'),('Muslim','Rowther'),('Muslim','Labbai'),('Muslim','Marakkayar'),('Muslim','Mapilla'),('Christian','Syrian Christian'),('Christian','Latin Catholic'),('Christian','Anglo-Indian'),('Christian','Dalit Christian'),('Christian','Nadar Christian'),('Christian','Mukkuvar Christian'),('Christian','Other Christian Community'),('Sikh','Jat Sikh'),('Sikh','Khatri'),('Sikh','Arora'),('Sikh','Ramgarhia'),('Sikh','Mazhabi Sikh'),('Sikh','Ravidasia'),('Sikh','Lubana'),('Sikh','Saini'),('Buddhist','Neo-Buddhist'),('Buddhist','Scheduled Caste Buddhist'),('Buddhist','Traditional Himalayan Buddhist'),('Jain','Digambar Jain'),('Jain','Shwetambar Jain'),('Jain','Oswal'),('Jain','Agarwal Jain'),('Jain','Porwal'),('Jain','Khandelwal Jain');
notify pgrst,'reload schema';

