-- Interest-request lifecycle is maintained by:
-- supabase/migrations/20261009183000_interest_request_lifecycle.sql
--
-- This legacy standalone snippet is intentionally no longer executable. Applying
-- the former trigger from this file would bypass lifetime uniqueness, cancellation
-- rules, preserved history, and the sender/recipient authorization checks.
-- Apply the migration through the project's normal Supabase migration workflow.
