-- DEPRECATED: this historical setup snapshot is intentionally inert.
-- Apply the ordered Supabase migrations instead, especially
-- 20261009110000_profile_photo_replacements_and_review_audit.sql. Keeping an
-- older review function here would be able to overwrite the secure workflow.
