-- DEPRECATED: this historical setup snapshot is intentionally inert.
-- Apply the ordered Supabase migrations instead, especially
-- 20261009110000_profile_photo_replacements_and_review_audit.sql. The old
-- attach function updated profiles.image_url before moderation and must not be
-- reintroduced.
