'use client';
import {useEffect,useRef,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {syncServerSession} from '@/lib/auth/session-client';
type Announcement={id:string;title:string;message:string;recipient_count:number;created_at:string};
export default function AdminNotificationsPage(){
 const [rows,setRows]=useState<Announcement[]>([]),[title,setTitle]=useState(''),[message,setMessage]=useState(''),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[success,setSuccess]=useState('');
 const pending=useRef<{requestId:string;title:string;message:string}|null>(null);
 async function load(){setLoading(true);try{const {data:{session}}=await supabase.auth.getSession();if(session)await syncServerSession(session.access_token);const response=await fetch('/api/admin/notifications',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error);setRows(data);}catch(e){setError(e instanceof Error?e.message:'Unable to load announcements');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function publish(){setBusy(true);setError('');setSuccess('');const payload=pending.current??{requestId:crypto.randomUUID(),title:title.trim(),message:message.trim()};pending.current=payload;
 try{const response=await fetch('/api/admin/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error);pending.current=null;setSuccess('Saved to '+data.recipientCount+' member inboxes.');setPreview(false);setTitle('');setMessage('');await load();}catch(e){setError(e instanceof Error?e.message:'Publishing failed. Retry this request.');}finally{setBusy(false);}}
 return <div className="p-6 bg-card border border-border rounded-2xl text-foreground space-y-5"><h1 className="text-xl font-bold">Member announcements</h1><p>Send an in-app notification to active members. Suspended, banned, deleted and admin accounts are excluded.</p>{error&&<p role="alert" className="text-red-600">{error}</p>}{success&&<p role="status">{success}</p>}<form onSubmit={e=>{e.preventDefault();setPreview(true);setSuccess('');}} className="space-y-3"><label className="block">Title<input required minLength={3} maxLength={120} disabled={busy||preview} value={title} onChange={e=>setTitle(e.target.value)} className="block w-full p-3 border border-border bg-background rounded" /></label><label className="block">Message<textarea required minLength={3} maxLength={2000} disabled={busy||preview} value={message} onChange={e=>setMessage(e.target.value)} className="block w-full p-3 border border-border bg-background rounded" /></label>{!preview&&<button type="submit" className="underline">Preview announcement</button>}</form>{preview&&<section className="border border-border p-4 rounded"><h2 className="font-bold">{title}</h2><p className="whitespace-pre-wrap">{message}</p><div className="flex gap-5 mt-4"><button disabled={busy} onClick={publish} className="underline">{busy?'Publishing…':'Publish to member inboxes'}</button><button disabled={busy||Boolean(pending.current)} onClick={()=>setPreview(false)}>Edit</button></div></section>}<section><h2 className="font-bold">Saved announcements (latest 100)</h2><button onClick={()=>{setError('');void load();}} className="underline my-3">Refresh</button>{loading?<p>Loading…</p>:rows.length===0?<p>No announcements published.</p>:rows.map(row=><article className="border-t border-border py-3" key={row.id}><h3 className="font-bold">{row.title}</h3><p className="whitespace-pre-wrap">{row.message}</p><p className="text-sm">{row.recipient_count} inboxes · {new Date(row.created_at).toLocaleString()}</p></article>)}</section></div>;
}

